site_name: Applied Data Science
site_description: A Space to learn applied Data Science in intuitive ways
site_author: Deepak Singh
site_url: https://deepsai8.github.io/dsapp
repo_url: https://github.com/deepsai8/dsapp

copyright: "Copyright &copy; 2023 Deepak Singh"

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  font:
    text: Google Sans
    code: Regular
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/feedback.js

extra:
  analytics:
    provider: google
    property: G-QM2HQ2VHSY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-neutral-outline
          name: This page was just okay
          data: 3
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 5
          note: >- 
            Thanks for your feedback!
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deepsai8
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/deepaksingh8819


plugins:
  - plotly
  - markmap
  - search:
    separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
    minify_html: true

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
    permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly

nav:
  - Home: index.md
  - Examples:
    - Thoughts: thoughts.md
    - Markmap: markmap_01.md
  - Blog:
    - blog/index.md