site_name: Applied Data Science
site_description: A Space to learn applied Data Science in intuitive ways
site_author: Deepak Singh
site_url: https://deepsai8.github.io/dsapp
repo_url: https://github.com/deepsai8/dsapp

copyright: "Copyright &copy; 2023 Deepak Singh"

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - accent: cyan
  icon:
    repo: fontawesome/brands/github
  font:
    text: Google Sans
    code: Regular
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/feedback.js

extra:
  analytics:
    provider: google
    property: G-QM2HQ2VHSY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-neutral-outline
          name: This page was just okay
          data: 3
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 5
          note: >- 
            Thanks for your feedback!


plugins:
  - plotly
  - search
  - git-revision-date
  - git-revision-date-localized:
    enable_creation_date: True
    type: timeago

markdown_extensions:
  - pymdownx.superfences:
    custom_fences:
      - name: plotly
        class: mkdocs-plotly
        format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly

nav:
    - Home: index.md
    - Thoughts: thoughts.md